services:
  miner:
    image: ethereum/client-go:v1.10.26
    container_name: miner
    hostname: node
    entrypoint: ["/bin/sh", "-c"]
    command: ["/workspace/dapp/init.sh /workspace/dapp/mine.sh"]
    stdin_open: true
    tty: true
    ports:
      - "8545:8545"  # RPC 端口
      - "30303:30303"  # P2P 端口
    volumes:
      - ./opt/docker-project/eth/workspace:/workspace
    networks:
      ethnet:
        ipv4_address: 172.26.0.50

networks:
  ethnet:
    external: true 